apiVersion: v1
kind: ReplicationController
metadata:
  name: svc1
spec:
  replicas: 3
  selector:
    name: svc1
  template:
    metadata:
      labels:
        name: svc1
    spec:
      containers:
        - name: svc1
          image: valerylobachev/svc1:latest
          ports:
            - containerPort: 8080