apiVersion: v1
kind: ReplicationController
metadata:
  name: svc2
spec:
  replicas: 3
  selector:
    name: svc2
  template:
    metadata:
      labels:
        name: svc2
    spec:
      containers:
        - name: svc2
          image: valerylobachev/svc2:latest
          ports:
            - containerPort: 8081
