apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: svc2-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
   - secretName: svc2-tls-cert
  rules:
  - host: svc2.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: svc2
          servicePort: web