apiVersion: v1
kind: Service
metadata:
 name: webpod-service
 labels:
   app: webpod-service-label
spec:
 type: LoadBalancer
 ports:
 - port: 8081
   targetPort: 80
   protocol: TCP
 selector:
   version: "1.1"